from sqlalchemy import Column, Integer, String
from Base import Base

"""
Martin Leipert
martin.leipert@fau.de

Store a Dicom Series from Orthanc in an archive database
with the Object Realtional Mapper SQLAlchemy
"""


class ArchivedSeries(Base):
    __tablename__ = 'archived_series'

    # Identifiers -> Unique Orthanc ids -> Are generated by Orthanc autoamtically
    # The series ID
    _orthanc_series_id = Column(String, primary_key=True)
    # The Study id -> Layer above series
    _orthanc_study_id = Column(String)
    # The patient id -> Highest "layer"
    _orthanc_patient_id = Column(String)

    # Data which are specific for archiving
    # Date when it was archived
    _archiving_date = Column(String)
    # Directory where it was stored
    _archive_location = Column(String)

    # Constructor which takes all data for Storage
    def __init__(self, orthanc_series_id, orthanc_study_id, orthanc_patient_id, archiving_date, archive_location):
        self._orthanc_series_id = orthanc_series_id
        self._orthanc_study_id = orthanc_study_id
        self._orthanc_patient_id = orthanc_patient_id

        self._archiving_date = archiving_date
        self._archive_location = archive_location
